### ISSUE TITLE
Questions with regard to the bond with the next neighbor is part of a ring

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#11]
I have finished the ORCA module and is currently testing it.

In the paper, it is said that 

The automated fragment generation works in the following way: When a flexible dihedral is identified, the first three neighbors of the central atoms of that dihedral are by default taken as part of the fragment. Then, the next atoms are removed and the fragment is capped with a hydrogen atom unless: 

- (1) the bond with the next neighbor has a bond order larger than 1.75; 
- (2) the bond with the next neighbor is part of a ring; 
- (3) the current atom has an electronegativity in Pauling scale larger than 3.0 (to prevent unwanted intramolecular hydrogen bonds, e.g., an O–C bond is not replaced by a O–H). 

I wonder why (2)? It seems to me that it is ok to cap the toluene to benzene?

With regard to (3), I do agree that cutting C-O-C to C-O-H is bad, but cutting C-O-C to C seems ok to me?

**Comment by selimsami** [comment]
> * (2) the bond with the next neighbor is part of a ring;
> I wonder why (2)? It seems to me that it is ok to cap the toluene to benzene?

Toluene does not fit in this rule, since the C-C bond is not part of a ring, so it would indeed be cut to a benzene.
The rule says, "if the bond with the next neighbor is part of a ring", so for example cyclohexane would not be cut into fragments.


> * (3) the current atom has an electronegativity in Pauling scale larger than 3.0 (to prevent unwanted intramolecular hydrogen bonds, e.g., an O–C bond is not replaced by a O–H).
> With regard to (3), I do agree that cutting C-O-C to C-O-H is bad, but cutting C-O-C to C seems ok to me?

We always want to take the first 3 neighbors in the fragment (the default), so if you cut C-O-C into C, you artificially make one fragment smaller than usual. Cutting after 2 bonds is not a good idea I think. So, it will instead be cut after the final C.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the explanation. I'm testing a molecule 
[opt_0.xyz.zip](https://github.com/selimsami/qforce/files/7474525/opt_0.xyz.zip)

I would imagine that to test the central dihedral, the original molecule

![image](https://user-images.githubusercontent.com/6242032/140308342-4d34c838-18db-4d4d-8d85-15fb81572701.png)

will be cut to (obviously the hydrogens will be added properly)
![image](https://user-images.githubusercontent.com/6242032/140308539-a47a7688-c0b0-4d04-8163-6ef09f18bd71.png)

but it has been cut to
![image](https://user-images.githubusercontent.com/6242032/140308468-ff322cd8-c909-4ace-b98a-ece30b698a71.png)

This is the toluene to benzene transformation that I was talking about.

**Comment by xiki-tempula** [comment]
Oh, I see the first three neighbours. Sorry for the Confusion. I wonder where did you get the first three neighbour definitions? It seems to me that two neighbours would be fine as well. I know obviously, that the more conservative the more accurate it is.

**Comment by xiki-tempula** [comment]
Thank you.

**Comment by selimsami** [comment]
>I wonder where did you get the first three neighbour definitions? It seems to me that two neighbours would be fine as well.

Chemical intuition and practical experience. You can of course change the default value with the frag_threshold keyword to whichever value you prefer.


> I know obviously, that the more conservative the more accurate it is.

This is not always true actually. Larger fragments tend to cause all sorts of problems with hysteresis and what not. So if you show that a threshold of 2 is sufficient to capture the chemical environment of the dihedral, then you are better off with 2.
