### ISSUE TITLE
About the rotation of the methyl group

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#18]
I'm testing a sample molecule.
![image](https://user-images.githubusercontent.com/6242032/141277073-3b45f502-2383-4801-95da-2c79e2cd1678.png)
It seems that the potential of rotating the methyl group (stick) is giving a large energy deviation.
![scan_data_CC_H12C9O1_c08240069d2302aefe34ef147e3de1a7~1](https://user-images.githubusercontent.com/6242032/141277291-f31c5ccc-47cc-4627-a650-2654d02a4a5a.png)

I first suspect that it is a charge issue, but it seems that the charge of the three hydrogens in the methyl group are 0.135416, 0.109544, 0.107681 so this probably won't give such a large energy fluctuation.

I wonder if you mind having a check? Thank you.
Is it possible to have the topology file for the fragment as well? So I could see what is going wrong here.

Please find the example attached.
[Archive.zip](https://github.com/selimsami/qforce/files/7519776/Archive.zip)

The dihedral is scan_data_CC_H12C9O1_c08240069d2302aefe34ef147e3de1a7

**Comment by selimsami** [comment]
That does not look good. I'll have a look when I can.

> Is it possible to have the topology file for the fragment as well? So I could see what is going wrong here.

I suggest adding:

```
[scan]
method = gromacs
```

Then the dihedral scan is done by GROMACS (much faster), and you will also get all the fragment topologies and optimized geometries. Then you can investigate your issue further to narrow down the cause.

**Comment by xiki-tempula** [comment]
@selimsami Thanks for the advice, I wonder how do I use Gromacs to do the scan?
I have the setting files as
```
[ff]
charge_scaling = 1.0
[qm]
memory = 30000
n_proc = 12
[qm::software(gaussian)]
charge_method = esp
[scan]
method = gromacs
frag_threshold = 2
gromacs_exec = gmx_mpi
```
Then I run 
`qforce start -o settings`
However, the result that I got is still the input file for Gaussian.
```
          ____         ______
         / __ \       |  ____|
        | |  | |______| |__ ___  _ __ ___ ___
        | |  | |______|  __/ _ \| '__/ __/ _ \
        | |__| |      | | | (_) | | | (_|  __/
         \___\_\      |_|  \___/|_|  \___\___|

                     Selim Sami
            University of Groningen - 2020
            ==============================

Selected QM Software: "gaussian"
Necessary Hessian output files and the corresponding extensions are:
- out_file: ['out', 'log']
- fchk_file: ['fchk', 'fck']

NOTE: Automatic atom-type determination (used only for LJ interactions) is new. 
      Double check your atom types or enter them manually.

Calculating the MD hessian matrix elements...
Fitting the MD hessian parameters to QM hessian values
Done!

There are 3 unique flexible dihedrals.
3 of them are missing the scan data.
QM input files for them are created in: start_qforce/fragments
Exiting...
```
Please find the files attached
[Archive.zip](https://github.com/selimsami/qforce/files/7520713/Archive.zip)
.

**Comment by selimsami** [comment]
It seems you're simply missing the QM dihedral scan output?

Gaussian is still used for the QM part.

GROMACS will be used for the MD scan (assuming that you already have the QM data)

**Comment by xiki-tempula** [comment]
@selimsami 
Sorry, I thought that given that most of the time spend on the dihedral scan is in the geometry optimisation, this option is to use GMX to generate the geometry optimised dihdedral coordinate.

Well, it seems that using the gmx MD engine solves the problem
![scan_data_CC_H12C9O1_c08240069d2302aefe34ef147e3de1a7~1](https://user-images.githubusercontent.com/6242032/141308870-527ae33a-08fc-4465-aa2f-e3852c6e49f4.png)
.
If you are interested, here is the whole file.
[Archive.zip](https://github.com/selimsami/qforce/files/7520818/Archive.zip)

**Comment by selimsami** [comment]
Great. Then probably it is an issue with the MD geometry optimization. GROMACS optimizer seems to be better than the scipy one.

I normally use GROMACS for the MD engine, I suggest you to do the same.
