### ISSUE TITLE
Use white space to delimit the space between parameters of the dihedral

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#24]
I got a case where during dihedral fitting, the Gromacs complain about 

```
ERROR 1 [file start_qforce.itp, line 211]:
  Incorrect number of parameters - found 5, expected 6 or 12 for
  Ryckaert-Bell. (after the function type).
```

Then I go to the topology file and see

```
; flexible dihedrals 
;   ai    aj    ak    al     f         c0         c1         c2         c3         c4         c5
     4     1     2     5     3-1709495.083 176801.341-2978144.451-155163.4584810154.416 -48007.179
     3     1     2     5     3-1710086.484-468573.252-746894.600 585004.0091104581.403 -57876.573
     1     2     5    10     3 -76256.092  68144.009 177037.976-250971.352-179383.273 184107.418
     1     2     5    11     3 -75363.665  46734.959  43046.945   -536.811 100235.507-163505.199
```

This is the step00 of the fitting so I think the numbers could have a problem.

I think one could do two things.

- Cap the absolute dihedral restraint strength to a maximum number like 10000.
- Delimit the numbers with a space.

**Comment by selimsami** [comment]
It looks like your dihedral fitting exploded. Best to see why this happened rather than trying to fix the error. This will not converge to a reasonable value even if you fix the GROMACS error.

Keep in mind that this is step00 of the current iteration, so probably something went wrong in the previous iterations.

**Comment by selimsami** [comment]
This should be fixed with the latest commit
