### ISSUE TITLE
Frame NBO reader such that it could read any NBO output

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#25]
The current NBO reader rely on arbitrary indices
https://github.com/selimsami/qforce/blob/e51178fe33f279a3bb08c1a3383ab59ecd67fc83/qforce/qm/qm_base.py#L89
https://github.com/selimsami/qforce/blob/e51178fe33f279a3bb08c1a3383ab59ecd67fc83/qforce/qm/qm_base.py#L90

However, these are not the correct indices for the ORCA 5.0.1/NBO 7.0
It might be good to have a general solution to cope with different NBO outputs.

**Comment by selimsami** [comment]
With #56 , this is no longer relevant
