### ISSUE TITLE
About using ORCA as QM engine

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#3]
Very nice tool! I wonder if it is possible to use ORCA as QM engine?
If I were to add the support for orca myself? I wonder what are functions that I need to modify? Thank you.

**Comment by selimsami** [comment]
Hi Zhiyi,

Thanks, glad you like it!
ORCA is not implemented yet, but you could definitely do this!

You would need to add a new module named orca.py in the [qm/](https://github.com/selimsami/qforce/tree/master/qforce/qm) directory and implement read/write of Hessian+scan output/input files (see also the 4 functions you need to implement in the [base class](https://github.com/selimsami/qforce/blob/master/qforce/qm/qm_base.py)). You can also use the [Gaussian](https://github.com/selimsami/qforce/blob/master/qforce/qm/gaussian.py) or [Q-Chem](https://github.com/selimsami/qforce/blob/master/qforce/qm/qchem.py) modules as an example and to see which QM properties you need. 

Afterwards, you only need to add your module to the [implemented_qm_software](https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/qm.py#L11) dictionary and the rest is taken care of automatically: ORCA will appear as an option in both input and documentation.

Of course you can ask me for help at any point if you get stuck or have any questions.

Cheers,
Selim

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the response. I have had a test run and I wonder if I can have more explanation with regard to the setting?

So I can see that the first one would be

`#Opt Freq PBEPBE EmpiricalDispersion=GD3BJ 6-31+G(D) pop=(CM5, ESP, NBOREAD)`

I wonder if PBE/6-31+G* is hardcoded into the run or it could be changed? So I will need to know if I could hard code it during the ORCA runs.

I wonder if I can use other ways of deriving the charge? For example, RESP. OR if the charge could be supplied to the program.

I wonder what are the ESP and NBO analysis for? So I would know if I need them for the orca as well.

**Comment by selimsami** [comment]
> I wonder if PBE/6-31+G* is hardcoded into the run or it could be changed? So I will need to know if I could hard code it during the ORCA runs.

It is not hardcoded. PBE/6-31+G* is simply the default value. You can set variables for Orca (like basis set, functional, charge method) in the _questions variable (see the Gaussian[ example](https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/gaussian.py#L10))

Then the user, when running qforce, can include in the options file (with the -o flag) non-default values. For example, the basis set and functional would be changed with:

```
[qm::software(orca)]
method = b3lyp
basis = cc-pvdz
```

There are also similar examples in the Q-Force [tutorials](https://qforce.readthedocs.io/en/latest/examples.html).

> I wonder if I can use other ways of deriving the charge? For example, RESP. OR if the charge could be supplied to the program.

You can implement whichever charge method you prefer, even multiple methods. Then again, you can add the option in _questions which charge method user wants to choose. For [example](https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/gaussian.py#L12) in Gaussian CM5 and ESP are implemented and the user can choose between them.


> I wonder what are the ESP and NBO analysis for? So I would know if I need them for the orca as well.

ESP is an alternative to CM5 for deriving charges. You can skip this, as long as you have a different charge method.

NBO analysis is used for bond orders and this is needed to determine rigid and flexible dihedrals, double/single bonds in the molecule. What I exactly need from NBO is: n_bonds (how many bonds each atom has), b_orders (bond order matrix), lone_e (how many lone electrons each atom has). I would guess ORCA has a way of computing these as well, probably with NBO analysis, but I have no experience with it.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the explanation. I noticed that during the dihedral scan, the input file is 

#Opt=Modredundant PBEPBE EmpiricalDispersion=GD3BJ 6-31+G(D) pop=(CM5, ESP)

I would imagine that the CM5 and ESP are only for charge fitting and this is done before the dihedral fitting (https://qforce.readthedocs.io/en/latest/method.html). So the pop=(CM5, ESP) has no use during the dihedral fitting stage. I wonder if my understanding is correct? 

Also, do you do a final single point energy calculation for the dihedral scan or the PBE/6-31+G* is the final reference dihedral energy?

**Comment by selimsami** [comment]
> I would imagine that the CM5 and ESP are only for charge fitting and this is done before the dihedral fitting (https://qforce.readthedocs.io/en/latest/method.html). So the pop=(CM5, ESP) has no use during the dihedral fitting stage. I wonder if my understanding is correct?

This was indeed correct until recently. However, to avoid spurious large charges during fragmentation on the capping atoms, the scan of fragments are now done with recomputed fragment charges. That's why the charges during the scan is useful/necessary. The code will still run without them though, it will just use the charges from the whole molecule, which in my experience can lead to unrealistic behavior during the relaxed scans.

> Also, do you do a final single point energy calculation for the dihedral scan or the PBE/6-31+G* is the final reference dihedral energy?

I am not sure what you mean by that. There are no single point calculations: each dihedral scan step is a relaxed optimization (i.e., rest of the geometry is optimized while the scanned dihedral is restrained).

**Comment by xiki-tempula** [comment]
@selimsami Thanks for the explanation.
I guess when I do QM calculations, I usually do the geometry optimisation at a low level of theory (as the optimal geometry derived from low level of theory will not differ too much from that with high level of theory but would be much faster) and compute the energy at a high level of theory.

**Comment by selimsami** [comment]
Ah I see now. This would not be possible for the Hessian, but indeed could be done for the scans. This is not currently implemented though. You could, however, include it in the ORCA implementation. Just a matter of which input files you create and which ones you read.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the explanation. As for the Hessian fitting, is it only performed once in the initial geometry optimisation as is shown here https://qforce.readthedocs.io/en/latest/method.html?

**Comment by selimsami** [comment]
Yes it is.

**Comment by xiki-tempula** [comment]
@selimsami Thank you very much for all the help. I wonder if I can ask another question? Thanks.

So in theory, for a molecule with N atoms, the hessian will be an 3N*3N matrix. Obviously, the upper and lower triangle is the same.

I wonder how does qforce store the hessian? For a sample hessian matrix of

```
1 2 3
2 4 5
3 5 6
```

If the hessian [1, 2, 3, 4, 5, 6] or [1, 2, 4, 3, 5, 6]? Or in another sense is it the upper of the lower triangle?

**Comment by xiki-tempula** [comment]
@selimsami Thank you very much for all the help. Another question is I wonder what is the lone pair of electrons for? ORCA could do NBO analysis but would need users to obtain their own NBO software, so I was wondering if one could do the calculation without giving the lone pair of electrons. The bond order matrix and bond valence could be obtained via Mayer population analysis though.

**Comment by selimsami** [comment]
> So in theory, for a molecule with N atoms, the hessian will be an 3N*3N matrix. Obviously, the upper and lower triangle is the same.
> 
> I wonder how does qforce store the hessian?

Since it's a triangle, the shape is: ((n_atoms*3)**2+n_atoms*3)/2)
It should be the upper triangle, if I'm not mistaken. It is the same as the fchk format.

> Another question is I wonder what is the lone pair of electrons for? ORCA could do NBO analysis but would need users to obtain their own NBO software, so I was wondering if one could do the calculation without giving the lone pair of electrons. The bond order matrix and bond valence could be obtained via Mayer population analysis though.

It helps determine the equivalent atoms and atom types. You could probably come up with an approximate value for them by substracting the total bond order of the atom from its valence electrons.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the answer, I felt the numbers are a bit wrong and it seems that the Gaussian hessian is written as lower triangle. I wonder if you will need to change the code to account for that?

```
Please find the attached reply from Gaussian

          The short answer is that symmetric matrices like the force constants are reported in lower triangular form.   

           You can see this fairly quickly if you examine the magnitude of the force constants where you expect the diagonal elements to be significantly larger than the off diagonal elements so for example running a simple water calculation you will see,

Cartesian Force Constants                  R   N=          45
-6.87891467E-05 -1.07433561E-15  7.15725957E-01 -8.66184350E-16  7.04297731E-16
  4.35617634E-01  3.43945729E-05 -2.53704783E-17 -5.01939308E-17 -4.22458907E-05
-5.27879015E-17 -3.57862978E-01  1.82931378E-01 -9.57521019E-18  3.95349801E-01
  4.44849437E-17  2.61566124E-01 -2.17808817E-01  1.17009395E-17 -2.22248751E-01
  2.04461004E-01  3.43945729E-05  9.74524949E-16  7.55237841E-16  7.85131772E-06
  3.48765487E-17 -2.87207151E-17 -4.22458907E-05  9.51514212E-16 -3.57862978E-01
-1.82931378E-01  5.78785971E-17 -3.74868226E-02 -3.93173730E-02 -8.56725108E-16
  3.95349801E-01  6.72107730E-16 -2.61566124E-01 -2.17808817E-01  5.43892620E-17
  3.93173730E-02  1.33478130E-02 -5.92821720E-16  2.22248751E-01  2.04461004E-01

where clearly the third element on the first line could only be the H1y-H1y term.   But with small cases you can also get the matrix reported in the output using #P rather than # on the route

Force constants in Cartesian coordinates: 
                1             2             3             4             5
      1 -0.687891D-04
      2  0.000000D+00  0.715726D+00
      3  0.000000D+00  0.000000D+00  0.435618D+00
      4  0.343946D-04  0.000000D+00  0.000000D+00 -0.422459D-04
...

and you can see the correspondence clearly.
```

**Comment by selimsami** [comment]
Okay, after your comment I decided to check more carefully, Q-Force does indeed store and deal with lower triangles also.

Have a look [here](https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/hessian.py#L15) where the 2D MM matrix is converted to lower triangle form.

Sorry for the confusion.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for all the help. I noticed that the elements in hessian are outputted as a list of atomic number. I wonder if there is a convenient function in force that convert element string (C) to atomic number (6)? Thank you.

**Comment by selimsami** [comment]
No worries, happy to help!

In the [elements module](https://github.com/selimsami/qforce/blob/master/qforce/elements.py), you can find the tuples you need to convert.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the help. I'm nearly there. As for the dihedral scan, orca would require the starting point. I wonder if it is possible to obtain the starting dihedral angle in degree? Thank you.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for all the help, I think I'm getting there. For the scan, I wonder how many points should I provide?
Say for example, if we have a step size of 90. Do I give [0, 90, 180, 270, 360] or [0, 90, 180, 270,] ? 
In orca, the former will need 5 steps and the latter will need four steps.

However, the gaussian will need https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/gaussian.py#L137
which is 3 steps, so I'm a bit confused.
Thank you.

**Comment by xiki-tempula** [comment]
@selimsami Thank you for the help. I wonder if there is some file that will write the current progress?
I'm currently working on the dihedral scan module. 
I write the code to make the input, then I generate the dihedral scan input file, then I noticed that something is wrong.
So I removed the fragments folder, modified the code and regenerate the input files.

I noticed that the file name has gone from CO_H10C10N2O3_ff1ead45b85fb8873df139752b8b97eb~1.inp to CO_H10C10N2O3_ff1ead45b85fb8873df139752b8b97eb~2.inp to CO_H10C10N2O3_ff1ead45b85fb8873df139752b8b97eb~3.inp. I would assume that something is keeping track of my modifications and I wonder if I can have clarification of that? Thank you.

**Comment by xiki-tempula** [comment]
@selimsami Another question, I wonder if it is better to change 
https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/qm.py#L107
to `files = [file for file in all_files if any(file.endswith(f'{ext}') for ext in texts)]`?

The tricky thing is that for a molecule with the name of RVXOH, if we supplement the basename with _opt during the initial hessian fitting.
The optimised file will have the name of `RVXOH_opt.xyz`
However, the folder will also contain `init.xyz`, which is created by qforce and `RVXOH_opt_trj.xyz`, which is the whole optimisation trajectory.

So if we change it such that it recognised the later part of the file, we could make it that

```
        self.required_hessian_files = {'out_file': ['out', 'log'],
                                       'coord_file': ['_opt.xyz'],}
```
Such that only one xyz file is being picked up.

**Comment by selimsami** [comment]
> @selimsami Thank you for all the help, I think I'm getting there. For the scan, I wonder how many points should I provide? Say for example, if we have a step size of 90. Do I give [0, 90, 180, 270, 360] or [0, 90, 180, 270,] ? In orca, the former will need 5 steps and the latter will need four steps.

The behavior you want is: [0, 90, 180, 270,], since 0 and 360 are identical

> 
> However, the gaussian will need
> 
> https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/gaussian.py#L137
> 
> which is 3 steps, so I'm a bit confused.

This sounds like a difference between ORCA and Gaussian.
For Gaussian, if steps=3, it will do [0, 90, 180, 270,], since it doesnt count 0 as a step.
For ORCA, just do what is necessary to get [0, 90, 180, 270,].

**Comment by selimsami** [comment]
> @selimsami Thank you for the help. I wonder if there is some file that will write the current progress? I'm currently working on the dihedral scan module. I write the code to make the input, then I generate the dihedral scan input file, then I noticed that something is wrong. So I removed the fragments folder, modified the code and regenerate the input files.
> 
> I noticed that the file name has gone from CO_H10C10N2O3_ff1ead45b85fb8873df139752b8b97eb~1.inp to CO_H10C10N2O3_ff1ead45b85fb8873df139752b8b97eb~2.inp to CO_H10C10N2O3_ff1ead45b85fb8873df139752b8b97eb~3.inp. I would assume that something is keeping track of my modifications and I wonder if I can have clarification of that? Thank you.

Q-Force creates in your home directory a directory called "qforce_fragments" where it stores all the previous fragments it encountered during a scan (more info on this in the [Q-Force article](https://pubs.acs.org/doi/10.1021/acs.jctc.1c00195)). It is possible that as you changed the code, you changed the job settings, so they were recognized as different fragments. Simply remove the "qforce_fragments" directory and it will reset.

The " _method" [variable ](https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/gaussian.py#L25) (also in qm.py) determines which job settings are relevant for identifying the calculation. Just to give an example the "scan_step_size" is used to identify the job settings, but requested memory or # of cores is not.

**Comment by selimsami** [comment]
> @selimsami Another question, I wonder if it is better to change
> 
> https://github.com/selimsami/qforce/blob/fca97157ace17700c540f0d4fe50c1b4d8bd376f/qforce/qm/qm.py#L107
> 
> 
> to `files = [file for file in all_files if any(file.endswith(f'{ext}') for ext in texts)]`?

This should be fine, would need to add a "." to all the other software extensions though. Also texts>exts.


> The tricky thing is that for a molecule with the name of RVXOH, if we supplement the basename with _opt during the initial hessian fitting. The optimised file will have the name of `RVXOH_opt.xyz` However, the folder will also contain `init.xyz`, which is created by qforce and `RVXOH_opt_trj.xyz`, which is the whole optimisation trajectory.
> 
> So if we change it such that it recognised the later part of the file, we could make it that
> 
> ```
>         self.required_hessian_files = {'out_file': ['out', 'log'],
>                                        'coord_file': ['_opt.xyz'],}
> ```
> 
> Such that only one xyz file is being picked up.

Why do you need a coordinate file? Can you not read the optimized coordinates from the output file?

**Comment by xiki-tempula** [comment]
@selimsami Thanks for the explanation. 

> Why do you need a coordinate file? Can you not read the optimized coordinates from the output file?

Yes, the information is in the output file. For me, this is kind of pure laziness, I found that if I determine the final coordinate based on some string, I will need to consider several cases. Given that orca has already provided the final optimised geometry as an xyz file, I find it easier to just read it and the user could just open the XYZ file to examine if the geometry is all right.

**Comment by selimsami** [comment]
Up to you, but I find it best to have the least number of required files as possible, most people use Q-Force on their local computer and run the calculations in the cluster, then they have to copy back additional files.

Also, Q-Force will anyway write the optimized geometry in gas.gro, so actually you are creating a duplicate.

**Comment by kexul** [comment]
It might be good if the ML potential could be supported as well, such as torchani and schnet, which is much faster. But I'm not sure if it's viable since only energy and force can be derived from the model.

**Comment by selimsami** [comment]
Hi Kexul, energy and force wouldn't be sufficient for a QM engine. Q-Force also needs bond orders, charges, etc.

**Comment by kexul** [comment]
Thank @selimsami for the reply!

**Comment by xiki-tempula** [comment]
@kexul I think there might also be a problem with the hessian which I think torchani is not doing super well.

**Comment by kexul** [comment]
> @kexul I think there might also be a problem with the hessian which I think torchani is not doing super well.

Hi @xiki-tempula ，thanks for the attention，I'm not expert in forcefield，but after some searching, I found that someone has done so: 10.1021/acs.jcim.9b00439
