### ISSUE TITLE
The force constant for the improper dihedral

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#38]
I was wondering how is improper dihedral defined in the Qforce? Or it is not defined and relays entirely on the proper dihedral? Thank you.
I have a test molecule secondary amine, which has planar nitrogen.

```
10
amine - input geometry
N        0.00000000      -1.05400000       0.00000000
C        1.26500000      -0.45300000      -0.01900000
C       -1.26500000      -0.45300000       0.01900000
H        0.00000000      -2.07200000       0.00000000
H       -2.03400000      -1.22500000       0.03100000
H       -1.36000000       0.16700000       0.91000000
H       -1.38700000       0.16700000      -0.86900000
H        2.03400000      -1.22500000      -0.03100000
H        1.36000000       0.16700000      -0.91000000
H        1.38700000       0.16700000       0.86900000
```

The qforce would give 0 force constant for the improper dihedral of 
`     1     2     3     4     2      0.000        0.000 `

**Comment by selimsami** [comment]
Hi,

Could you share the ZIP file with the necessary files?

It does put improper potentials as necessary but it is possible that it was not necessary in this case and angle and Urey-Bradley terms were sufficient.

I would look at the vibrational frequencies/modes and see if there is a problem with that Hydrogen's out of plane motion. (I would guess not)

**Comment by xiki-tempula** [comment]
@selimsami Please find the zip file attached.
I do agree that Urey-Bradley terms might be sufficient. I'm just wondering if the Qforce will explicitly parametrise the improper dihedral as the improper are always zero in my test cases.
[Archive.zip](https://github.com/selimsami/qforce/files/7977768/Archive.zip)

**Comment by selimsami** [comment]
Do you have a test case that isn't a Hydrogen?

I have couple of test cases with heavy atoms with non-zero impropers. For example acetic acid.

**Comment by xiki-tempula** [comment]
@selimsami I can see it now.
Sorry, my fault. I used to think dihedral type 1 and 9 of proper dihedral and 4 for improper dihedral.
I have just noticed that type 2 is improper dihedral as well.
