### ISSUE TITLE
Implement a plugin to use Torsion Drive

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#39]
I'm thinking of having an option to use Torsion Drive/xTB to do the geometry optimisation in Torsion Scan.

I was thinking of making such an interface

Where the input would be the same as the `qforce/qforce/qm/qm_base.py:WriteABC.scan()`

Which is the `coords, atnums, scanned_atoms, charge, multiplicity` and the output would be `coords_list, atnums, dihedral_list`.
The `coords_list` is a list of geometry optimised coordinates, which would be feed into the QM energy for single point energy calculations.

I wonder where should I put it?

I was thinking of make a function in `qforce/qforce/qm/qm_base.py:WriteABC.TorsionDrive()`, which is then called by other QM methods.

**Comment by selimsami** [comment]
I think implementation of Torsiondrive should be independent of xTB and would be an alternative to the normal scan option. The QM methods that support Torsiondrive (Gaussian, xTB, ...?) would have an extra keyword "use_torsiondrive" that calls the plugin instead of doing the normal relaxed scan. Does that make sense or do you foresee problems regarding that?

Additionally, if your intention is to do optimization with xTB and single point with a method of choice, xTB/Gaussian interface (which is almost ready), could be useful for that. Then you would need to interface Gaussian with Torsiondrive instead of xTB though. 

Would that address your use case? If not, please tell me in a bit more detail in what sort of pipeline do you intend to use the Torsiondrive/xTB interface.

**Comment by xiki-tempula** [comment]
So the plan of this issue and the later PR would be `have an extra keyword "use_torsiondrive" that calls the plugin instead of doing the normal relaxed scan`
However, the problem is that Torsiondrive only supports Gaussian/psi4/Qchem and I tried to add xTB to the list. So the overlap would be Gaussian and xTB.

However, I think I would probably only implement the xTB engine for the Torsiondrive due to two reasons.

- I no longer have access to Gaussian but I don't know if we would acquire it in the future. We are currently buying ORCA.
- From my experience, using Torsiondrive/Gaussian is super slow so from my perspective, it might not be super useful and xTB might be sufficient.

> Additionally, if your intention is to do optimization with xTB and single point with a method of choice, xTB/Gaussian interface (which is almost ready), could be useful for that. Then you would need to interface Gaussian with Torsiondrive instead of xTB though.

The pipeline that I'm currently interested in is passing a GAFF or openff (the openff can wait) small molecule force field into Qforce, The Qforce identifies the soft torsions and call the Torsiondrive/xTB to generate the torsion conformations. The conformations are then passed to software such as ORCA for single point energy (or even constrained optimisation using xTB output conformation as input conformation). Then the conformations, energy are used to refit the force field.

**Comment by selimsami** [comment]
Ok that clarifies things, thanks!

Then one option is to implement:
1. xTB as a standalone QM engine for Q-Force (Hessian + dihedral scan), same as all other QM engines
2. for the QM dihedral scan part,  interface xTB with Torsiondrive

So the keyword here would be "dihedral_scanner", which in your case would be torsiondrive and for other QM methods would be "relaxed_scan". And that would be make interfacing other QM methods to Torsiondrive easy in the future.

This would also help you skip the #40 for now, since you can just use xTB Hessian.

---

Option 2 would be to implement only an xTB/Torsiondrive interface.

Then each QM method can choose "dihedral_scanner = xtb-torsiondrive", which uses your interface to get optimized geometries, and the QM method can perform single point calculations. Here, might be good to give also the option to only use xTB single point energies, then we could do the test we discussed in private to compare those two options.


What do you think?

**Comment by xiki-tempula** [comment]
I think I like option 2 more. The xTB hessian might be ok but the xTB energy for torsion profile definitely needs improvement. There is also the issue of partial charge.

To get this implemented. I will implement the qforce/qforce/qm/qm_base.py:WriteABC.torsiondrive(), which takes the same input as qforce/qforce/qm/qm_base.py:WriteABC.scan(). qforce/qforce/qm/qm_base.py:ReadABC.torsiondrive() which gives the same return as qforce/qforce/qm/qm_base.py:ReadABC.scan().

I will also implement the ORCA version qforce/qforce/qm/orca.py:WriteORCA.torsiondrive() and qforce/qforce/qm/orca.py: ReadORCA.torsiondrive(), which does the single point energy calculation. I'm afraid that I cannot implement the Gaussian version before I have access to Gaussian but I could help if you have encountered difficulty.

Do you mind implement it such that when "dihedral_scanner = xtb-torsiondrive", the torsiondrive write and read function will be used?

With regard to the `option to only use xTB single point energies`, For ORCA, I think if one set qm_method_sp to None, the xTB energy would be used. As one would still need the ORCA to get the partial charge.

**Comment by selimsami** [comment]
> To get this implemented. I will implement the qforce/qforce/qm/qm_base.py:WriteABC.torsiondrive(), which takes the same input as qforce/qforce/qm/qm_base.py:WriteABC.scan(). qforce/qforce/qm/qm_base.py:ReadABC.torsiondrive() which gives the same return as qforce/qforce/qm/qm_base.py:ReadABC.scan().

Sounds good!

> I will also implement the ORCA version qforce/qforce/qm/orca.py:WriteORCA.torsiondrive() and qforce/qforce/qm/orca.py: ReadORCA.torsiondrive(), which does the single point energy calculation. I'm afraid that I cannot implement the Gaussian version before I have access to Gaussian but I could help if you have encountered difficulty.

Sounds good. I will use your ORCA template to implement Gaussian/Q-Chem. I assume much of implementation will be in qm_base.py, right? What is the QM software dependent part? Your step-wise implementation (hessian/scan/sp methods) in ORCA is more suitable for this approach. Maybe that's one thing I will need to change in other software. For ORCA, "if dihedral_scanner = xtb-torsiondrive, use torsiondrive interface for the optimization" will be sufficient, right?

> Do you mind implement it such that when "dihedral_scanner = xtb-torsiondrive", the torsiondrive write and read function will be used?

Sounds good!

> With regard to the option to only use xTB single point energies, For ORCA, I think if one set qm_method_sp to None, the xTB energy would be used. As one would still need the ORCA to get the partial charge.

Great! Then I might follow a similar approach for other QM methods.

**Comment by xiki-tempula** [comment]
> Sounds good. I will use your ORCA template to implement Gaussian/Q-Chem. I assume much of implementation will be in qm_base.py, right? 

Yes.

> What is the QM software dependent part? 

For partial charge and if user wants the single point energy.

> Your step-wise implementation (hessian/scan/sp methods) in ORCA is more suitable for this approach. Maybe that's one thing I will need to change in other software. For ORCA, "if dihedral_scanner = xtb-torsiondrive, use torsiondrive interface for the optimization" will be sufficient, right?

I will need your help to make it that if `dihedral_scanner = xtb-torsiondrive`, use ReadABC.torsiondrive() instead of ReadABC.scan() and WriteABC.torsiondrive() instead of WriteABC.scan(). Otherwise, I think it should be fine.

**Comment by selimsami** [comment]
I am working/thinking about this now.
Two questions:

1.  Do you intend to do DFT SP calculations only at the end of the full torsiondrive procedure? Or at the end of every xTB constrained optimization during the torsiondrive procedure?
2. Do you intend to call torsiondrive/xtb from within Q-Force?

**Comment by xiki-tempula** [comment]
> Do you intend to do DFT SP calculations only at the end of the full torsiondrive procedure? Or at the end of every xTB constrained optimization during the torsiondrive procedure?

Initially only SP calculations. Later on may or may not.

> Do you intend to call torsiondrive/xtb from within Q-Force?

Yes, my PR to TorsionDrive should enable it to be used as a function.

**Comment by selimsami** [comment]
yes only SP calculations - but will this be only on the final scan path determined by Torsiondrive (with xTB energies)?

**Comment by xiki-tempula** [comment]
> but will this be only on the final scan path determined by Torsiondrive (with xTB energies)?

Yes. This is my plan. I wonder what is your suggestion?

**Comment by selimsami** [comment]
I think it is fine - just keep in mind that you would then be using xTB energies to determine your final scan path, which you earlier called not too reliable.

Alternative would be to do a DFT SP at the end of every relaxed scan in torsiondrive. But this complicates things since then ORCA/Torsiondrive/xTB have to interact many times.

But I am happy with the first option also.

**Comment by xiki-tempula** [comment]
> I think it is fine - just keep in mind that you would then be using xTB energies to determine your final scan path, which you earlier called not too reliable.

 I guess the main aim of TorsionDrive is to give reasonable conformation (doesn't have to be the real lowest energy but should be reasonably low). However, at the end of the day these are all speculations and one needs to test to see how it goes.

**Comment by selimsami** [comment]
So with some more thought, I feel it might be best to implement this in qforce/qm.py

```
class QM(Colt):
    _user_input = """
# Use the internal relaxed scan method of the QM software or the Torsiondrive method using xTB
dihedral_scanner = relaxed_scan :: str :: [relaxed_scan, xtb-torsiondrive]

# If using xtb-torsiondrive as dihedral scanner, also do a single point energy calculation on optimized geometries with a different QM method
do_single_point = False :: bool
...
"""

    def write_scan(self, file, scan_id, coords, atnums, scanned_atoms, start_angle, charge, multiplicity):

        if self.config.dihedral_scanner == 'relaxed_scan':
            self.software.write().scan(file, scan_id, self.config, coords, atnums, scanned_atoms,
                                               start_angle, charge, multiplicity)

        elif self.config.dihedral_scanner == 'xtb-torsiondrive':
            coord_list = xtb_torsiondrive_interface(...)
            
            if self.config.do_single_point:
                 self.software.write().single_point(file, scan_id, self.config, coord_list, atnums, charge, multiplicity)

```

Similarly also for read_scan().

Then one only has to implement a single point calculation energy reader/writer for multiple geometries for each QM method.

What do you think?

**Comment by xiki-tempula** [comment]
@selimsami I'm happy with this interface. If we go this way then I guess then I don't need to wait for you to make the interface ready and could just start working on it.

**Comment by selimsami** [comment]
Great, let's do it like this then! I'll have my part up and ready next week.

**Comment by xiki-tempula** [comment]
@selimsami Within the write_scan, I wonder how can I access the current folder?
Say the fragment file will be created as propane_qforce/fragments/CC_H8C3_d91b46644317dee9c2b868166c66a18c~1.inp
I want to make a folder of `propane_qforce/fragments/CC_H8C3_d91b46644317dee9c2b868166c66a18c~1_Torsiondrive`. I wonder what is the best way of achieving this? Thanks.

**Comment by selimsami** [comment]
`self.job.frag_dir` should be your fragment directory. You can make a new subdirectory using that.

**Comment by xiki-tempula** [comment]
@selimsami Another api related thing.
So 
```
class QM(Colt):
    _user_input = """
# Use the internal relaxed scan method of the QM software or the Torsiondrive method using xTB
dihedral_scanner = relaxed_scan :: str :: [relaxed_scan, xtb-torsiondrive]

# If using xtb-torsiondrive as dihedral scanner, also do a single point energy calculation on optimized geometries with a different QM method
do_single_point = False :: bool
...
"""

    def write_scan(self, file, scan_id, coords, atnums, scanned_atoms, start_angle, charge, multiplicity):

        if self.config.dihedral_scanner == 'relaxed_scan':
            self.software.write().scan(file, scan_id, self.config, coords, atnums, scanned_atoms,
                                               start_angle, charge, multiplicity)

        elif self.config.dihedral_scanner == 'xtb-torsiondrive':
            coord_list = xtb_torsiondrive_interface(...)
```
The xtb_torsiondrive_interface would return dihedral list which is the dihedral of each coordinate (e.g. `[-165, -150, ..., 180]`) and energy list which corresponds to each coordinates. I wonder what is the perfered way of passing this information into the `read_scan`
I could create a file of `f'{job.frag_dir}/{scan_id}_torsiondrive.dat'`, in the format of
```
-165 -1.3
-150 -1.4
...
180  -1.5
```

**Comment by selimsami** [comment]
My suggestion would be:

- write_scan() can just write all the necessary torsiondrive-xtb folders and inputs.
- Then the user runs torsiondrive-xtb externally.
- read_scan() parses the torsiondrive output and obtains the coordinates/energy. (then the .dat file becomes unnecessary I guess? But could still have it).

Then it will be the same approach as all the other QM readers/writers.

**Comment by xiki-tempula** [comment]
@selimsami Thanks. I guess one issue would be the QM single point energy. Then between

Then the user runs torsiondrive-xtb externally.

and

read_scan() parses the torsiondrive output and obtains the coordinates/energy. (then the .dat file becomes unnecessary I guess? But could still have it).

One would need to call qforce again to read the torsiondrive output and generate the new QM input.

Given that torsiondrive-xtb runs very fast (usually less than half a minute) and even less in the parallel setting I think it might be good for the qforce to just run the torsiondrive-xtb internally.

**Comment by selimsami** [comment]
> Given that torsiondrive-xtb runs very fast (usually less than half a minute) and even less in the parallel setting I think it might be good for the qforce to just run the torsiondrive-xtb internally.

This might be true for small molecules but imagine if you're scanning 20 fragments of ~50 atoms, the user might want to have the option to submit them separately. I'm not sure if it will still be so quick in that case. Or for example if we start looking into 2D dihedrals.

Might be also an option to give the user the choice between internal/external.

But it's also not a big issue to add an extra line of qforce call in your bash script if it's external.

**Comment by xiki-tempula** [comment]
You are absolutely right and in the later stage, I will surly need to test that.
