### ISSUE TITLE
possibility of finding the scan output file in the same way as the hessian

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#41]
For the hessian, one could use 

        self.required_hessian_files = {'out_file': ['.out', '.log'],
                                       'hess_file': ['_opt.hess'],
                                       'pc_file': ['_charge.pc_chelpg'],
                                       'coord_file': ['_opt.xyz'],}

to find the relavent file.

Could one use the same procedure for the scan as well?
I got two output file and both of them ends with log.

**Comment by selimsami** [comment]
Could be. Was not necessary so far though. What kind of files are they?

**Comment by xiki-tempula** [comment]
@selimsami So we don't have access to Gaussian (yet and I don't know what is their plan). I write a xTB plugin and it seems that when xTB does the relaxed surface scan, it generates 
`CC_H8C12N2O1Cl2_aba2de1281620a8b1e1155817c6e45b5~1.xtbscan.log`
and
`CC_H8C12N2O1Cl2_aba2de1281620a8b1e1155817c6e45b5~1.xtbopt.log`
which both ends with log so I don't know which one will qforce pick up.

**Comment by xiki-tempula** [comment]
Ok, I solved the issue with a hack.

**Comment by selimsami** [comment]
I see. Not sure how you solved it, but one thing to keep in mind is that users can also provide 

CC_H8C12N2O1Cl2_aba2de1281620a8b1e1155817c6e45b5~1.log
CC_H8C12N2O1Cl2_aba2de1281620a8b1e1155817c6e45b5~1_anyname.log

and these will be read as two seperate output files and qforce will grab the lower energy scan points. See here:
https://github.com/selimsami/qforce/blob/923da5247a008dd13a14f5dd2a66b9e5b6ffc4c1/qforce/fragment.py#L292

I think it might be good to move this step from fragment to qm readers if we start needing different files.

**Comment by xiki-tempula** [comment]
I just did 

```
base, name = os.path.split(file_name)
name = name.split('.')[0]
'{}.xtbscan.log'.format(os.path.join(base, name)
```

I guess we need to change this somehow as torsiondrive produce scan.xyz as output file.

**Comment by xiki-tempula** [comment]
I guess the most versatile format will be giving the directory (self.job.frag_dir) and the fragment name (scan_id).

**Comment by xiki-tempula** [comment]
@selimsami I guess I might need some help with the best way of reading the xyz file as the scan output, as using ase to read log file in the format of xyz would lost all the comments.

Say I have a xyz file
```
3
comment
O 1 0 0
H 0 0 0
H 2 0 0
```
If I save the file in the format of 'test.xyz'
I could get the comment in the format of
```
>>> mol = ase.IO.read('test.xyz')
>>> print(list(mol.info.keys())
['comment',]
```
If I save the file in the format of 'test.log', and read it with format='xyz', the comment line would get lost.
```
>>> mol = ase.IO.read('test.log', format='xyz')
>>> print(list(mol.info.keys())
[]
```
So I think the best way would be allow the qforce to read in the xyz as scan output.

**Comment by selimsami** [comment]
Use extended xyz 'extxyz' as the format

**Comment by xiki-tempula** [comment]
Excellent. Thanks.
