### ISSUE TITLE
Reason for pulp<2.2

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#44]
So I was trying to use conda env during the CI and it seems that the inclusion of `pulp<2.2` would force the conda to select the python version to be <3.8. I wonder if there is any reason for this pining? Thanks.

**Comment by xiki-tempula** [comment]
I have removed the pin and it seems Qforce could run fine in py3.8/3.9.

In the CI, I have had an example of running Qforce from xyz file all the way to topology file using the xtb engine https://github.com/selimsami/qforce/blob/05926698f4b30946164e2a080e914ab7bc23fc8d/qforce/tests/test_run_xtb.py. Which seems to show that Qforce could handle the pulp without the pin.

**Comment by selimsami** [comment]
At the time the latest version of pulp was throwing errors (that I can no longer remember). If this is no longer the case, then it might be safe to remove it.

**Comment by selimsami** [comment]
> I have removed the pin and it seems Qforce could run fine in py3.8/3.9.
> 
> In the CI, I have had an example of running Qforce from xyz file all the way to topology file using the xtb engine https://github.com/selimsami/qforce/blob/05926698f4b30946164e2a080e914ab7bc23fc8d/qforce/tests/test_run_xtb.py. Which seems to show that Qforce could handle the pulp without the pin.

You specifically mentioned 3.8 and 3.9. Is it not working for 3.7?

**Comment by xiki-tempula** [comment]
@selimsami It is only working on 3.7, as pulp==2.1 require python<3.8.
