### ISSUE TITLE
Writing the default section

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#47]
So if I tried to set the extLJ, the writing of the default section is a bit problematic.
So the setting is
```
[ff]
lennard_jones = ext
charge_scaling = 1.0
ext_lj_fudge = 1.0
ext_q_fudge = 0.83333333
ext_comb_rule = 2
ext_h_cap = h1
ext_lj_lib = atomtypes.itp
```
The Default that is written down is

```
[ defaults ]
;nbfunc   comb-rule   gen-pairs   fudgeLJ   fudgeQQ
      1           2         yes       1.00.83333333
```
I think this formatting can be a bit problematic.

**Comment by selimsami** [comment]
That's a lot of 3's :-)

**Comment by xiki-tempula** [comment]
Just copy and paste from gaff

**Comment by selimsami** [comment]
This should be fixed with the latest commit
