### ISSUE TITLE
Remove the numpy from the install-requires

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#7]
The `numba` has a very strict requirement for `numpy`, so it might be better to allow `numba` to install the `numpy` as a requirement.

Currently, running `python setup.py install` will give `error: numpy 1.21.3 is installed but numpy<1.21,>=1.17 is required by {'numba'}`.

**Comment by selimsami** [comment]
@xiki-tempula , I removed the numpy version from the requirements. let me know if you encounter any issue please.
