### ISSUE TITLE
The default n_excl

### ISSUE THREAD

**Issue by xiki-tempula** [selimsami/qforce#8]
In https://qforce.readthedocs.io/en/latest/options.html, it is said that 

```
n_excl, int
 default: 2, from Choices(2, 3)
Number of first n neighbors to exclude in the forcefield
```

I wonder if this means that the default n_excl is 2? Instead of the commonly used 3?

**Comment by selimsami** [comment]
It does mean that. But I would say that commonly n_excl=2 is used. The 3rd neighbors are the 1-4 interactions, which are commonly not excluded but have special pair interactions. Q-Force follows the same approach as the parent transferable FF.

**Comment by xiki-tempula** [comment]
I see what you mean now. Sorry that I didn't read the description.  In Gromacs topology file, nrexcl is usually set to 3 so I thought that they are the same.

**Comment by selimsami** [comment]
Yeah I see why it is confusing, maybe worth renaming the variable. The GROMACS topology file will have nrexcl=3 with both n_excl 2 and 3, but in the former case, it will have the pair interactions turned on.
